In [1]:
import numpy as np

In [3]:
tDarray=np.arange(20).reshape(4,5)
tDarray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [5]:
tDarray = np.random.randn(20).reshape(5,4)

In [6]:
tDarray

array([[-0.00746114,  2.18741178, -0.47896333, -0.71652832],
       [ 0.38149035, -1.10442005,  0.88625011,  0.23225894],
       [ 0.69720368,  1.11642867, -1.35413524, -1.26675079],
       [ 1.64874346,  0.31411   ,  0.40114014,  0.11124607],
       [-0.36095284, -0.12512648, -1.41235147,  0.52348501]])

In [8]:
tDarray=np.arange(20).reshape(4,5)
tDarray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [9]:
tDarray[3,2]

17

In [10]:
tDarray[1,3]

8

In [11]:
tDarray[2,1]

11

In [12]:
tDarray[1,]

array([5, 6, 7, 8, 9])

In [15]:
tDarray[1:3,1:3].ndim

2

In [17]:
tDarray[1:3,1:2].ndim

2

In [18]:
tDarray[0:3,1:3]

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

In [19]:
tDarray[5:7,1:3]

array([], shape=(0, 2), dtype=int32)

In [24]:
tDarray[3:3,1:3]

array([], shape=(0, 2), dtype=int32)

In [31]:
tDarray[1:3,3:5]

array([[ 8,  9],
       [13, 14]])

In [32]:
tDarray[:,4]

array([ 4,  9, 14, 19])

In [34]:
tDarray[:,0]

array([ 0,  5, 10, 15])

In [39]:
tDarray[3:4,0:5]

array([[15, 16, 17, 18, 19]])

In [40]:
tDarray[3,:]

array([15, 16, 17, 18, 19])

In [41]:
t=tDarray[3,]

In [42]:
t[4]=9999

In [43]:
t

array([  15,   16,   17,   18, 9999])

In [44]:
tDarray[3,]

array([  15,   16,   17,   18, 9999])

In [45]:
tDarray

array([[   0,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14],
       [  15,   16,   17,   18, 9999]])

In [46]:
p=tDarray[3,:]

In [47]:
p[3]=999

In [48]:
p

array([  15,   16,   17,  999, 9999])

In [49]:
tDarray

array([[   0,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14],
       [  15,   16,   17,  999, 9999]])

In [50]:
tDarray[1:3,3:5]

array([[ 8,  9],
       [13, 14]])

In [51]:
c=tDarray[1:3,3:5]

In [52]:
c

array([[ 8,  9],
       [13, 14]])

In [54]:
c[1,1]=555

In [55]:
c

array([[  8,   9],
       [ 13, 555]])

In [56]:
tDarray

array([[   0,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9],
       [  10,   11,   12,   13,  555],
       [  15,   16,   17,  999, 9999]])

In [57]:
d3=np.arange(100).reshape(5,5,4)

In [58]:
d3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]],

       [[60, 61, 62, 63],
        [64, 65, 66, 67],
        [68, 69, 70, 71],
        [72, 73, 74, 75],
        [76, 77, 78, 79]],

       [[80, 81, 82, 83],
        [84, 85, 86, 87],
        [88, 89, 90, 91],
        [92, 93, 94, 95],
        [96, 97, 98, 99]]])

In [59]:
d3[2,3,1]

53

In [61]:
d3[2,2:4,1:3]

array([[49, 50],
       [53, 54]])

In [62]:
d3[2:4,2:4,1:3]

array([[[49, 50],
        [53, 54]],

       [[69, 70],
        [73, 74]]])

In [63]:
d3[2,3:4,1:3]

array([[53, 54]])

In [64]:
d3[2:5,2:4,1:3]

array([[[49, 50],
        [53, 54]],

       [[69, 70],
        [73, 74]],

       [[89, 90],
        [93, 94]]])

In [68]:
a=np.array([[[[[[[[[[10]]]]]]]]]])

In [69]:
a

array([[[[[[[[[[10]]]]]]]]]])

In [70]:
a.ndim

10

In [71]:
a=np.arange(5)

In [72]:
a

array([0, 1, 2, 3, 4])

In [73]:
a>3

array([False, False, False, False,  True])

In [74]:
a>2 and a<4

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [75]:
d3[[1,3,4],1]

array([[24, 25, 26, 27],
       [64, 65, 66, 67],
       [84, 85, 86, 87]])

In [76]:
d3[1]

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])